### ISSUE TITLE
Added close with Esc feature.

### ISSUE THREAD

**Issue by jorgerc85** [echoThat/echo_that_extension#14]
This was not in our list of features but I thought it would be a nice feature to have, I didn't make a PR yet because of the same reason. You guys can test it and I'll make a PR if you agree to add it.

**Comment by lukert33** [comment]
I just spun through the escape key functionality. It's excellent. I was about to put a PR in myself, but it probably makes more sense for me to be the one to merge it. So throw it up when you have a moment.
