### ISSUE TITLE
Char count sensing

### ISSUE THREAD

**Issue by lukert33** [echoThat/echo_that_extension#5]
@mikeh0rn this may be one for you as you'd implemented the original feature.

The char count doesn't respond when I highlight and delete a chunk of text to downsize my echo. It only evaluates with the correct count once I add more text.

This had the weird effect of not evaluating a new count when I added an @mention that put the count over 140, then deleted the whole @mention with a highlight. The count didn't change.

Would attaching the char count event listeners to keyups while the form is active be a way to solve this?

**Comment by mikeh0rn** [comment]
@lukert33 Just had to change the echoLeftWrapper event listener to keyup instead of keydown and that did the trick. Since it's just a 1 word update, I can either push up my branch or you can update it on master - whichever you prefer/is easier. Let me know.

**Comment by jorgerc85** [comment]
@mikeh0rn @lukert33 I made some refactoring to contentscript, I'll add that change in my branch

**Comment by lukert33** [comment]
Just merged the change in with the fix. Thanks dudes!
